#pragma once

// Application
#define IDR_MAINMENU 101
#define IDI_APPICON  201

// Dialogs
#define IDD_PREFERENCES 301

// Menus
#define ID_FILE_ADDTORRENT 9001
#define ID_FILE_EXIT 9002
#define ID_VIEW_PREFERENCES 9101

// Preferences dialog
#define ID_PREFS_DEFSAVEPATH 9101
#define ID_PREFS_LISTENPORT 9102
#define ID_PREFS_PROMPTFORSAVEPATH 9103
#define ID_PREFS_DEFSAVEPATH_BROWSE 9104

// Torrent context menu
#define IDR_TORRENT_CONTEXT_MENU 4100
#define TORRENT_CONTEXT_MENU_PAUSE 4101
#define TORRENT_CONTEXT_MENU_RESUME 4102
#define TORRENT_CONTEXT_MENU_RESUME_FORCE 4103
#define TORRENT_CONTEXT_MENU_MOVE 4104
#define TORRENT_CONTEXT_MENU_REMOVE 4105
#define TORRENT_CONTEXT_MENU_COPY_SHA 4106
#define TORRENT_CONTEXT_MENU_COPY_MAGNET 4107
#define TORRENT_CONTEXT_MENU_OPEN_IN_EXPLORER 4108

// NotifyIcon context menu
#define IDR_NOTIFYICON_CONTEXT_MENU 4200
#define ID_NOTIFYICON_ADD 4201
#define ID_NOTIFYICON_EXIT 4202
