#pragma once

#define IDC_STATIC -1

// Strings
#define IDS_PREFS_DOWNLOADS_TITLE 101
#define IDS_PREFS_CONNECTION_TITLE 102
#define IDS_PREFS_ADVANCED_TITLE 103

// Keyboard accelerators
#define IDR_PICO_ACCELERATORS 8000
#define IDA_SELECT_ALL 8001
#define IDA_REMOVE_TORRENTS 8002
#define IDA_REMOVE_TORRENTS_DATA 8003

// Application
#define IDR_MAINMENU 101
#define IDI_APPICON  201

// Dialogs
#define IDD_PREFERENCES 301
#define IDD_ABOUT 302
#define IDD_ADD_TORRENT 303

// Menus
#define ID_FILE_ADDTORRENT 9001
#define ID_FILE_EXIT 9002
#define ID_VIEW_PREFERENCES 9101
#define ID_HELP_ABOUT 9201

// Preferences dialog
#define ID_PREFS_DEFSAVEPATH 9101
#define ID_PREFS_LISTENPORT 9102
#define ID_PREFS_PROMPTFORSAVEPATH 9103
#define ID_PREFS_DEFSAVEPATH_BROWSE 9104
#define ID_PREFS_PROXY_TYPE 9105
#define ID_PREFS_PROXY_HOST 9106
#define ID_PREFS_PROXY_PORT 9107
#define ID_PREFS_PROXY_USERNAME 9108
#define ID_PREFS_PROXY_PASSWORD 9109
#define ID_PREFS_PROXY_FORCE 9110
#define ID_PREFS_PROXY_HOSTNAMES 9111
#define ID_PREFS_PROXY_PEERS 9112
#define ID_PREFS_PROXY_TRACKERS 9113

// Torrent context menu
#define IDR_TORRENT_CONTEXT_MENU 4100
#define TORRENT_CONTEXT_MENU_PAUSE 4101
#define TORRENT_CONTEXT_MENU_RESUME 4102
#define TORRENT_CONTEXT_MENU_RESUME_FORCE 4103
#define TORRENT_CONTEXT_MENU_MOVE 4104
#define TORRENT_CONTEXT_MENU_REMOVE 4105
#define TORRENT_CONTEXT_MENU_REMOVE_DATA 4106
#define TORRENT_CONTEXT_MENU_COPY_SHA 4107
#define TORRENT_CONTEXT_MENU_COPY_MAGNET 4108
#define TORRENT_CONTEXT_MENU_OPEN_IN_EXPLORER 4109

// Torrent file context menu
#define IDR_TORRENT_FILE_MENU 4400
#define TORRENT_FILE_PRIO_SKIP 4401
#define TORRENT_FILE_PRIO_NORMAL 4402
#define TORRENT_FILE_PRIO_HIGH 4403
#define TORRENT_FILE_PRIO_MAX 4404


// NotifyIcon context menu
#define IDR_NOTIFYICON_CONTEXT_MENU 4200
#define ID_NOTIFYICON_ADD 4201
#define ID_NOTIFYICON_EXIT 4202

// About dialog
#define ID_ABOUT_ICON 4300

// Keyboard shortcuts
#define IDHOT_SELECT_ALL 1001
