#pragma once

#include <atlres.h>

#define IDR_MAINFRAME 1280
#define IDD_ADDTORRENT 2280
#define IDD_RENAMEFILE 3280

#define ID_FILE_ADD_TORRENT 4000
#define ID_FILE_EXIT ID_APP_EXIT

#define ID_TORRENTCTX_PAUSE IDR_MAINFRAME+1
#define ID_TORRENTCTX_RESUME IDR_MAINFRAME+2
#define ID_TORRENTCTX_MANAGED IDR_MAINFRAME+3
#define ID_TORRENTCTX_RECHECK IDR_MAINFRAME+4
#define ID_TORRENTCTX_REMOVE IDR_MAINFRAME+5

#define ID_ADDTORRENT_GROUP_TORRENTS IDD_ADDTORRENT+1
#define ID_ADDTORRENT_TORRENTS IDD_ADDTORRENT+2
#define ID_ADDTORRENT_SIZE IDD_ADDTORRENT+3
#define ID_ADDTORRENT_COMMENT IDD_ADDTORRENT+4
#define ID_ADDTORRENT_CREATIONDATE IDD_ADDTORRENT+5
#define ID_ADDTORRENT_CREATOR IDD_ADDTORRENT+6
#define ID_ADDTORRENT_GROUP_STORAGE IDD_ADDTORRENT+7
#define ID_ADDTORRENT_SAVEPATH IDD_ADDTORRENT+8
#define ID_ADDTORRENT_BROWSE IDD_ADDTORRENT+9
#define ID_ADDTORRENT_FILES IDD_ADDTORRENT+10
#define ID_ADDTORRENT_FILES_MENU IDD_ADDTORRENT+11
#define ID_ADDTORRENT_RENAME_FILE IDD_ADDTORRENT+12
#define ID_ADDTORRENT_PRIO_MAX IDD_ADDTORRENT+13
#define ID_ADDTORRENT_PRIO_HIGH IDD_ADDTORRENT+14
#define ID_ADDTORRENT_PRIO_NORMAL IDD_ADDTORRENT+15
#define ID_ADDTORRENT_PRIO_DND IDD_ADDTORRENT+16

#define ID_RENAMEFILE_NAME IDD_RENAMEFILE+1
